name: Deploy VPC with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  TF_WORKING_DIR: ./

permissions:
  id-token: write   # Required for OIDC
  contents: read    # To checkout the repo

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan

      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.9.0
        with:
          approvers: vipul2996
          secret: ${{ secrets.PAT_TOKEN }}
        if: success()

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve

